export const themes = {
  dark: {
    name: 'Dark Modern',
    background: '#0d0d0d',
    surface: '#1a1a1a',
    text: '#f5f5f5',
    accent: '#8b5cf6',
    secondary: '#6366f1',
    description: 'Sleek dark theme with vibrant accents',
  },
  light: {
    name: 'Light Clean',
    background: '#f9fafb',
    surface: '#ffffff',
    text: '#111827',
    accent: '#6366f1',
    secondary: '#8b5cf6',
    description: 'Bright and airy professional theme',
  },
  elegantDark: {
    name: 'Elegant Business',
    background: '#0a0e1a',
    surface: '#151b2e',
    text: '#e8eaf0',
    accent: '#c9a55a',
    secondary: '#8b7355',
    gradient: 'linear-gradient(135deg, #0a0e1a 0%, #151b2e 50%, #1a2338 100%)',
    description: 'Sophisticated dark theme with gold accents',
  },
  corporate: {
    name: 'Corporate Blue',
    background: '#f8f9fb',
    surface: '#ffffff',
    text: '#1e293b',
    accent: '#0f4c81',
    secondary: '#2563eb',
    gradient: 'linear-gradient(135deg, #f8f9fb 0%, #e8eef5 100%)',
    description: 'Professional blue theme for business',
  },
  platinum: {
    name: 'Platinum Suite',
    background: '#f5f5f7',
    surface: '#ffffff',
    text: '#1d1d1f',
    accent: '#5e5ce6',
    secondary: '#64d2ff',
    gradient: 'linear-gradient(135deg, #f5f5f7 0%, #ffffff 50%, #fafafa 100%)',
    description: 'Minimalist luxury design',
  },
  midnight: {
    name: 'Midnight Executive',
    background: '#0f1419',
    surface: '#1a1f2e',
    text: '#f0f0f0',
    accent: '#00d4ff',
    secondary: '#0ea5e9',
    gradient: 'linear-gradient(135deg, #0f1419 0%, #1a1f2e 50%, #242b3d 100%)',
    description: 'Modern dark with cyan highlights',
  },
};
