#!/usr/bin/env node
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const requiredKeys = [
  'VITE_FIREBASE_API_KEY',
  'VITE_FIREBASE_AUTH_DOMAIN',
  'VITE_FIREBASE_PROJECT_ID',
  'VITE_FIREBASE_STORAGE_BUCKET',
  'VITE_FIREBASE_SENDER_ID',
  'VITE_FIREBASE_APP_ID',
  'VITE_FIREBASE_MEASUREMENT_ID',
  'VITE_API_BASE',
  'VITE_OPENAI_API_KEY',
  'VITE_STRIPE_PUBLIC_KEY',
  'VITE_STRIPE_WEBHOOK_SECRET',
  'VITE_BI_REPORTS_ENABLED'
];

const placeholderValues = {
  VITE_FIREBASE_API_KEY: 'your-firebase-api-key',
  VITE_FIREBASE_AUTH_DOMAIN: 'your-project.firebaseapp.com',
  VITE_FIREBASE_PROJECT_ID: 'your-firebase-project-id',
  VITE_FIREBASE_STORAGE_BUCKET: 'your-project.appspot.com',
  VITE_FIREBASE_SENDER_ID: '000000000000',
  VITE_FIREBASE_APP_ID: '1:000000000000:web:example',
  VITE_FIREBASE_MEASUREMENT_ID: 'G-XXXXXXXXXX',
  VITE_API_BASE: 'https://api.example.com',
  VITE_OPENAI_API_KEY: 'sk-your-openai-key',
  VITE_STRIPE_PUBLIC_KEY: 'pk_test_your_stripe_key',
  VITE_STRIPE_WEBHOOK_SECRET: 'whsec_your_webhook_secret',
  VITE_BI_REPORTS_ENABLED: 'false'
};

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(__dirname, '..');
const envFiles = ['.env', '.env.local', '.env.development', 'amplify.env'];

const readEnvFile = (filePath) => {
  if (!fs.existsSync(filePath)) {
    return {};
  }

  const content = fs.readFileSync(filePath, 'utf8');
  return Object.fromEntries(
    content
      .split(/\r?\n/)
      .map((line) => line.trim())
      .filter((line) => line && !line.startsWith('#'))
      .map((line) => {
        const [key, ...rest] = line.split('=');
        return [key.trim(), rest.join('=').trim()];
      })
  );
};

const aggregateEnv = () => {
  const env = { ...process.env };
  envFiles.forEach((filename) => {
    const fileEnv = readEnvFile(path.join(projectRoot, filename));
    Object.assign(env, fileEnv);
  });
  return env;
};

const ensureExampleFile = () => {
  const examplePath = path.join(projectRoot, '.env.local.example');
  const currentEntries = readEnvFile(examplePath);
  let didChange = false;

  requiredKeys.forEach((key) => {
    if (!currentEntries[key]) {
      currentEntries[key] = placeholderValues[key] ?? '';
      didChange = true;
    }
  });

  const sortedKeys = Object.keys(currentEntries).sort();
  const banner = '# Auto-generated by scripts/validateEnv.mjs\n';
  const body = sortedKeys.map((key) => `${key}=${currentEntries[key]}`).join('\n');
  const finalContent = `${banner}${body}\n`;

  if (didChange || !fs.existsSync(examplePath) || fs.readFileSync(examplePath, 'utf8') !== finalContent) {
    fs.writeFileSync(examplePath, finalContent, 'utf8');
    console.log('Updated .env.local.example with required keys.');
  }
};

const env = aggregateEnv();
const missingKeys = requiredKeys.filter((key) => !env[key] || env[key].length === 0);

ensureExampleFile();

if (missingKeys.length) {
  console.error('\nMissing required environment variables:');
  missingKeys.forEach((key) => {
    console.error(` - ${key}`);
  });
  console.error('\nPopulate one of the environment files (.env, .env.local, amplify.env) or set the variables in the shell and re-run the script.');
  process.exitCode = 1;
} else {
  console.log('✅ All required environment variables are present.');
}
