import PageHeader from '../../components/common/PageHeader.jsx';
import { useAuth } from '../../context/AuthContext.jsx';
import { useTenant } from '../../context/TenantContext.jsx';

const Card = ({ title, description, children }) => (
  <div className="rounded-2xl border border-white/10 bg-white/5 p-6 shadow-[0_0_30px_rgba(12,10,40,0.35)]">
    <h2 className="text-lg font-semibold text-white">{title}</h2>
    <p className="mt-2 text-sm text-white/60">{description}</p>
    <div className="mt-4 space-y-3 text-sm text-white/80">{children}</div>
  </div>
);

export default function Security() {
  const { role } = useAuth();
  const { brand } = useTenant();

  return (
    <div className="px-4 pb-16">
      <PageHeader
        title="Enterprise Security"
        subtitle="Configure SSO, enforce 2FA, and audit cross-tenant access for enterprise workspaces."
      />
      <p className="mb-6 rounded-xl border border-white/10 bg-white/5 p-4 text-sm text-white/70">
        Signed in as <strong>{role}</strong>. Security policies apply to the <strong>{brand?.name || 'Hustle Studio'}</strong>
        workspace.
      </p>
      <div className="grid gap-6 lg:grid-cols-2">
        <Card title="SSO Providers" description="Enable Google or Microsoft sign-in for workspace members.">
          <label className="flex items-center justify-between rounded-lg border border-white/10 bg-black/30 p-3">
            <span>Google Workspace</span>
            <input type="checkbox" className="h-5 w-5" defaultChecked />
          </label>
          <label className="flex items-center justify-between rounded-lg border border-white/10 bg-black/30 p-3">
            <span>Microsoft Entra ID</span>
            <input type="checkbox" className="h-5 w-5" />
          </label>
          <p className="text-xs text-white/50">
            Configure redirect URIs inside your identity provider dashboard. Updates propagate instantly to login.
          </p>
        </Card>
        <Card title="Authentication Policies" description="Strengthen access with two-factor prompts and session limits.">
          <label className="flex items-center justify-between rounded-lg border border-white/10 bg-black/30 p-3">
            <span>Require 2FA for admins</span>
            <input type="checkbox" className="h-5 w-5" defaultChecked />
          </label>
          <label className="flex items-center justify-between rounded-lg border border-white/10 bg-black/30 p-3">
            <span>Auto-expire sessions after 14 days</span>
            <input type="checkbox" className="h-5 w-5" defaultChecked />
          </label>
          <label className="flex items-center justify-between rounded-lg border border-white/10 bg-black/30 p-3">
            <span>Restrict API access to whitelisted IP ranges</span>
            <input type="checkbox" className="h-5 w-5" />
          </label>
        </Card>
        <Card title="Audit Trails" description="Monitor sensitive actions across API and dashboard.">
          <ul className="space-y-2 text-xs">
            <li>• API key generated by Admin (just now)</li>
            <li>• Billing plan upgraded to Pro (2 hours ago)</li>
            <li>• 2FA enforced for all members (yesterday)</li>
          </ul>
          <p className="text-xs text-white/50">Detailed logs live under <code>telemetry</code> for compliance exports.</p>
        </Card>
        <Card title="Incident Response" description="Automated alerts route to your security contacts via Slack or WhatsApp.">
          <p>Security notifications send to the workspace escalation list.</p>
          <button
            type="button"
            className="rounded-full bg-gradient-to-r from-red-500 to-rose-500 px-4 py-2 text-xs font-semibold text-white shadow-[0_10px_25px_rgba(244,63,94,0.35)]"
          >
            Trigger Test Alert
          </button>
        </Card>
      </div>
    </div>
  );
}
